import { reactive, readonly } from 'vue'

const state = reactive({
  locale: localStorage.getItem('locale') || 'en',
})

const messages = {
  en: {
    navProblems: 'Problems', navAdmin: 'Admin', navLogin: 'Login', navSignup: 'Sign Up', navLogout: 'Logout',
    footerText: '© 2026 AlgoPlatform — Learn Algorithms efficiently.',
    homeHero1: 'Master Algorithms.', homeHero2: 'Level up your code.',
    homeSubtitle: 'A platform designed to help you prepare for technical interviews and competitive programming with a premium environment.',
    homeStartCoding: 'Start Coding', homeCreateAccount: 'Create Account',
    loginTitle: 'Welcome Back', loginSubtitle: 'Enter your credentials to continue',
    loginEmail: 'Email', loginPassword: 'Password',
    loginEmailPlaceholder: 'coder@example.com', loginPasswordPlaceholder: '••••••••',
    loginSubmit: 'Sign In', loginLoading: 'Authenticating...', loginFailed: 'Login failed. Please check credentials.',
    loginFooter: 'New to AlgoPlatform?', loginFooterLink: 'Create an account',
    registerTitle: 'Join AlgoPlatform', registerSubtitle: 'Start your algorithmic mastery journey',
    registerUsername: 'Username', registerUsernamePlaceholder: 'coder_ninja',
    registerEmail: 'Email', registerEmailPlaceholder: 'ninja@example.com',
    registerPassword: 'Password', registerPasswordPlaceholder: 'Min 8 characters',
    registerSubmit: 'Sign Up', registerLoading: 'Creating Account...', registerFailed: 'Failed to register account.',
    registerFooter: 'Already have an account?', registerFooterLink: 'Sign In',
    problemsTitle: 'Algorithm Challenges', problemsSubtitle: 'Select a problem to solve and improve your algorithmic skills.',
    problemsLoading: 'Loading challenges...', problemsEmpty: 'No problems available yet.',
    problemsError: 'Failed to load problems. Please try again.', problemsAddedOn: 'Added on', problemsSolve: 'Solve Challenge',
    detailBack: '← Back to problems', detailExamples: 'Examples', detailInput: 'Input:', detailOutput: 'Expected Output:',
    detailRunCode: 'Run Code', detailSubmitting: 'Submitting...', detailResult: 'Submission Result',
    detailRefresh: 'Refresh Status', detailLoading: 'Loading challenge...', detailWriteCode: 'Write your code here...', detailSampleTest: 'Sample test',
    adminTitle: 'Admin Problem Management', adminSubtitle: 'Create, update, and delete algorithm problems.',
    createSection: 'Create Problem', manageSection: 'Manage Existing',
    adminStatements: 'Statements', adminTests: 'Tests', adminRemove: 'Remove',
    adminAddStatement: '+ Add statement', adminAddTest: '+ Add test',
    adminSaving: 'Saving...', adminCreate: 'Create', adminLoadById: 'Load by ID',
    adminUpdating: 'Updating...', adminUpdate: 'Update', adminDelete: 'Delete', adminDeleting: 'Deleting...',
    adminDeleteProblem: 'Delete Problem', adminExisting: 'Existing Problems', adminRefresh: 'Refresh',
    adminNoProblems: 'No problems yet.', adminLoading: 'Loading...',
    adminInput: 'input', adminExpected: 'expected output',
    adminSlugPlaceholder: 'slug (e.g. two-sum)', adminProblemIdPlaceholder: 'problem id',
    adminNewSlugPlaceholder: 'new slug', adminTitlePlaceholder: 'title', adminStatementPlaceholder: 'problem statement',
  },
  ru: {
    navProblems: 'Задачи', navAdmin: 'Админ', navLogin: 'Вход', navSignup: 'Регистрация', navLogout: 'Выйти',
    footerText: '© 2026 AlgoPlatform — Учись алгоритмам эффективно.',
    homeHero1: 'Освой алгоритмы.', homeHero2: 'Прокачай свой код.',
    homeSubtitle: 'Платформа для подготовки к техническим собеседованиям и олимпиадному программированию в качественной среде.',
    homeStartCoding: 'Начать решать', homeCreateAccount: 'Создать аккаунт',
    loginTitle: 'С возвращением', loginSubtitle: 'Введите данные для входа',
    loginEmail: 'Электронная почта', loginPassword: 'Пароль',
    loginEmailPlaceholder: 'coder@example.com', loginPasswordPlaceholder: '••••••••',
    loginSubmit: 'Войти', loginLoading: 'Вход...', loginFailed: 'Ошибка входа. Проверьте данные.',
    loginFooter: 'Нет аккаунта?', loginFooterLink: 'Создать аккаунт',
    registerTitle: 'Присоединяйся', registerSubtitle: 'Начни свой путь к мастерству алгоритмов',
    registerUsername: 'Имя пользователя', registerUsernamePlaceholder: 'coder_ninja',
    registerEmail: 'Электронная почта', registerEmailPlaceholder: 'ninja@example.com',
    registerPassword: 'Пароль', registerPasswordPlaceholder: 'Минимум 8 символов',
    registerSubmit: 'Зарегистрироваться', registerLoading: 'Создание аккаунта...', registerFailed: 'Ошибка регистрации.',
    registerFooter: 'Уже есть аккаунт?', registerFooterLink: 'Войти',
    problemsTitle: 'Задачи по алгоритмам', problemsSubtitle: 'Выберите задачу и улучшайте свои навыки.',
    problemsLoading: 'Загрузка задач...', problemsEmpty: 'Задач пока нет.',
    problemsError: 'Не удалось загрузить задачи. Попробуйте снова.', problemsAddedOn: 'Добавлено', problemsSolve: 'Решить задачу',
    detailBack: '← Назад к задачам', detailExamples: 'Примеры', detailInput: 'Ввод:', detailOutput: 'Ожидаемый вывод:',
    detailRunCode: 'Запустить', detailSubmitting: 'Отправка...', detailResult: 'Результат отправки',
    detailRefresh: 'Обновить статус', detailLoading: 'Загрузка задачи...', detailWriteCode: 'Напишите код здесь...', detailSampleTest: 'Примерный тест',
    adminTitle: 'Управление задачами', adminSubtitle: 'Создание, редактирование и удаление задач.',
    createSection: 'Создать задачу', manageSection: 'Управление существующими',
    adminStatements: 'Условия', adminTests: 'Тесты', adminRemove: 'Удалить',
    adminAddStatement: '+ Добавить условие', adminAddTest: '+ Добавить тест',
    adminSaving: 'Сохранение...', adminCreate: 'Создать', adminLoadById: 'Загрузить по ID',
    adminUpdating: 'Обновление...', adminUpdate: 'Обновить', adminDelete: 'Удалить', adminDeleting: 'Удаление...',
    adminDeleteProblem: 'Удалить задачу', adminExisting: 'Существующие задачи', adminRefresh: 'Обновить',
    adminNoProblems: 'Задач пока нет.', adminLoading: 'Загрузка...',
    adminInput: 'ввод', adminExpected: 'ожидаемый вывод',
    adminSlugPlaceholder: 'slug (например, two-sum)', adminProblemIdPlaceholder: 'id задачи',
    adminNewSlugPlaceholder: 'новый slug', adminTitlePlaceholder: 'заголовок', adminStatementPlaceholder: 'условие задачи',
  },
  tm: {
    navProblems: 'Meseleler', navAdmin: 'Admin', navLogin: 'Giriş', navSignup: 'Hasaba al', navLogout: 'Çyk',
    footerText: '© 2026 AlgoPlatform — Algoritmleri netijeli öwren.',
    homeHero1: 'Algoritmleri öwren.', homeHero2: 'Kodlamaňy ýokarlandyr.',
    homeSubtitle: 'Tehniki söhbetdeşliklere we bäsleşik programmirlemesine taýýarlanmak üçin platforma.',
    homeStartCoding: 'Başla', homeCreateAccount: 'Hasap döret',
    loginTitle: 'Hoş geldiňiz', loginSubtitle: 'Dowam etmek üçin maglumatlary giriziň',
    loginEmail: 'Ulanyjynyň ady', loginPassword: 'Parol',
    loginEmailPlaceholder: 'coder@example.com', loginPasswordPlaceholder: '••••••••',
    loginSubmit: 'Giriş', loginLoading: 'Girilýär...', loginFailed: 'Giriş başa barmady. Maglumatlary barlaň.',
    loginFooter: 'AlgoPlatformda ýok bolsaňyz?', loginFooterLink: 'Hasap döret',
    registerTitle: 'AlgoPlatforma goşul', registerSubtitle: 'Algoritm ussatlyk ýoluňy başla',
    registerUsername: 'Ulanyjy ady', registerUsernamePlaceholder: 'coder_ninja',
    registerEmail: 'E-poçta', registerEmailPlaceholder: 'ninja@example.com',
    registerPassword: 'Parol', registerPasswordPlaceholder: 'Min 8 simwol',
    registerSubmit: 'Hasaba al', registerLoading: 'Hasap döredilýär...', registerFailed: 'Hasap döretmek başa barmady.',
    registerFooter: 'Hasabyňyz barmy?', registerFooterLink: 'Giriş',
    problemsTitle: 'Algoritm Meseleleri', problemsSubtitle: 'Çözmek üçin mesele saýlaň we başarnygyňyzy ýokarlandyryň.',
    problemsLoading: 'Meseleler ýüklenýär...', problemsEmpty: 'Heniz mesele ýok.',
    problemsError: 'Meseleleri ýükläp bolmady. Gaýtadan synanyşyň.', problemsAddedOn: 'Goşulan', problemsSolve: 'Çöz',
    detailBack: '← Meselelere dolan', detailExamples: 'Mysallar', detailInput: 'Giriş:', detailOutput: 'Garaşylýan çykyş:',
    detailRunCode: 'Kody işlet', detailSubmitting: 'Iberilýär...', detailResult: 'Iberme netijesi',
    detailRefresh: 'Statusy täzele', detailLoading: 'Mesele ýüklenýär...', detailWriteCode: 'Koduňyzy şu ýere ýazyň...', detailSampleTest: 'Nusga synag',
    adminTitle: 'Mesele Dolandyryşy', adminSubtitle: 'Mesele döretmek, täzelemek we pozmak.',
    createSection: 'Mesele döret', manageSection: 'Bar bolanlary dolandyrmak',
    adminStatements: 'Beýanlar', adminTests: 'Synlar', adminRemove: 'Poz',
    adminAddStatement: '+ Beýan goş', adminAddTest: '+ Syn goş',
    adminSaving: 'Saklanýar...', adminCreate: 'Döret', adminLoadById: 'ID boýunça ýükle',
    adminUpdating: 'Täzelenýär...', adminUpdate: 'Täzele', adminDelete: 'Poz', adminDeleting: 'Pozulýar...',
    adminDeleteProblem: 'Mesele poz', adminExisting: 'Bar bolan meseleler', adminRefresh: 'Täzele',
    adminNoProblems: 'Heniz mesele ýok.', adminLoading: 'Ýüklenýär...',
    adminInput: 'giriş', adminExpected: 'garaşylýan çykyş',
    adminSlugPlaceholder: 'slug (mysal, two-sum)', adminProblemIdPlaceholder: 'mesele id',
    adminNewSlugPlaceholder: 'täze slug', adminTitlePlaceholder: 'başlyk', adminStatementPlaceholder: 'mesele beýany',
  },
}

export function useUIStore() {
  const setLocale = (locale) => {
    state.locale = locale
    localStorage.setItem('locale', locale)
  }

  const t = (key) => messages[state.locale]?.[key] || messages.en[key] || key

  return {
    state: readonly(state),
    setLocale,
    t,
  }
}
